name: BoboBot
 
on:  workflow_dispatch

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 505600

    steps:
       - name: Initial setup
         uses: actions/checkout@master
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
     #  - uses: rokibhasansagar/slimhub_actions@main

         
       - name: Setup env
         continue-on-error: true
         timeout-minutes: 100
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect neofetch tmux tmate aria2
              git config --global user.name "spiderdev123"
              git config --global user.email "spidermanm7@hotmail.com"
              git clone https://spiderdev123:${{ secrets.token }}@github.com/spiderdev123/gsitools -b a12 ErfanGSIs
              curl -sL https://git.io/file-transfer | sh
     
       - name: Setup Erfan-Tools
         continue-on-error: true
         timeout-minutes: 10
         run: |
              sudo chmod -R 0777 ErfanGSIs
              sudo bash ErfanGSIs/setup.sh
       - name: Generate configs.prop
         continue-on-error: true
         timeout-minutes: 3
         run: |
              java -jar Bobo.jar
         
       - name: Setup values
         continue-on-error: true
         timeout-minutes: 1
         run: |
             rm -rf configs/configs.prop && rm -rf configs/sf-creds.prop
             cd configs
             touch configs.prop
             echo "#BoÂ³+t config file" >> "configs.prop"
             echo "#Sat Dec 25 12:03:12 GAZA/JERUSALEM PALESTINE 2021" >> "configs.prop"
             echo "bot-username=nibbagsibot" >> "configs.prop"
             echo "bot-token=${{ secrets.BOTKEY }}" >> "configs.prop"
             echo "bot-master=285384888" >> "configs.prop"
             touch sf-creds.prop
             echo "#Config file" >> "sf-creds.prop"
             echo "#Sat Dec 25 12:03:12 GAZA/JERUSALEM PALESTINE 2021" >> "sf-creds.prop"
             echo "bot-sf-user=nippon" >> "sf-creds.prop"
             echo "bot-send-announcement=true" >> "sf-creds.prop"
             echo "bot-sf-proj=nippongsi" >> "sf-creds.prop"
             echo "bot-announcement-id=-1001446520361" >> "sf-creds.prop"
             echo "bot-sf-pass=${{ secrets.SFPASS }}" >> "sf-creds.prop"
             echo "bot-sf-host=frs.sourceforge.net" >> "sf-creds.prop"
       - name: Start BOT
         continue-on-error: true
         timeout-minutes: 310
         run: |
              sudo chmod -R 0777 *
              sudo java -jar Bobo.jar
